spring:
  ai:
    ollama:
        base-url: http://127.0.0.1:11434
        init:
          pull-model-strategy: always #自动获取最新的模型
          timeout: 60s
          max-retries: 1
        chat:
          additional-models:
            - qwen3:8b # 除默认属性配置外需额外初始化的模型列表
          options:
            model: deepseek-r1:8b
