package com.example.ai.demo_ai.controller;

import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.ai.chat.prompt.Prompt;
//import org.springframework.ai.deepseek.DeepSeekAssistantMessage;
//import org.springframework.ai.deepseek.DeepSeekChatOptions;
//import org.springframework.ai.deepseek.api.DeepSeekApi;
import org.springframework.ai.ollama.OllamaChatModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;

import java.util.List;
import java.util.Map;

/**
 * @author 70635
 */
//@RestController
//@CrossOrigin("*")
public class DeepSeekChatController {
//    private final OllamaChatModel chatModel;
//
//    @Autowired
//    public DeepSeekChatController(OllamaChatModel chatModel) {
//        this.chatModel = chatModel;
//    }
//
//    @PostMapping("/ai/generate")
//    public Map generate(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
//        return Map.of("generation", this.chatModel.call(message));
//    }
//
//    @PostMapping("/ai/generateStream")
//    public Flux<ChatResponse> generateStream(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
//        Prompt prompt = new Prompt(new UserMessage(message));
//        return this.chatModel.stream(prompt);
//    }
//
//    @PostMapping("/ai/generatePythonCode")
//    public String generateDefine(@RequestParam(value = "message", defaultValue = "Please write quick sort code") String message) {
//        //聊天前缀补全
//        UserMessage userMessage = new UserMessage(message);
//        Message assistantMessage = DeepSeekAssistantMessage.prefixAssistantMessage("```python\\n");
//        Prompt prompt = new Prompt(List.of(userMessage, assistantMessage), ChatOptions.builder().stopSequences(List.of("```")).build());
//        ChatResponse response = chatModel.call(prompt);
//        return response.getResult().getOutput().getText();
//    }
//
//    public void deepSeekReasonerExample() {
//        DeepSeekChatOptions promptOptions = DeepSeekChatOptions.builder()
//                .model(DeepSeekApi.ChatModel.DEEPSEEK_REASONER.getValue())
//                .build();
//        Prompt prompt = new Prompt("9.11 and 9.8, which is greater?", promptOptions);
//        ChatResponse response = chatModel.call(prompt);
//
//        // Get the CoT content generated by deepseek-reasoner, only available when using deepseek-reasoner model
//        DeepSeekAssistantMessage deepSeekAssistantMessage = (DeepSeekAssistantMessage) response.getResult().getOutput();
//        String reasoningContent = deepSeekAssistantMessage.getReasoningContent();
//        String text = deepSeekAssistantMessage.getText();
//    }
}
